services:
  - type: web
    name: bulk-image-cropper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_cloud:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
